# Header
menu:
  Home: / || home
  Archives: /archives/ || archive
  categories: /categories/ || th           
  tags: /tags/ || tags                     
  about: /about/ || user 
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
#sidebar: right
#widgets:
#- category
#- tag
#- tagcloud
#- archive
#- recent_posts

sidebar:
# Sidebar Position - 侧栏位置（只对Pisces | Gemini两种风格有效）
  position: left        
  #position: right      

# Sidebar Display - 侧栏显示时机（只对Muse | Mist两种风格有效）
  #display: post        //默认行为，在文章页面（拥有目录列表）时显示
  display: always       
  #display: hide        //在所有页面中都隐藏（可以手动展开）
  #display: remove      //完全移除

  offset: 12            

  b2t: false            

  scrollpercent: true   

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Schemes
# scheme: Muse
# scheme: Mist
# scheme: Pisces
scheme: Gemini

local_search : 
   enable: true